### ISSUE TITLE
not working, getting error Lexical error on line 1. Unrecognized text. <?xml version="1.0" 

### ISSUE THREAD

**Issue by gg187on** [aressler38/gml2json#1]
```
Lexical error on line 1. Unrecognized text.
<?xml version="1.0" 
^
Error: Lexical error on line 1. Unrecognized text.
<?xml version="1.0" 
^
    at Parser.parseError (eval at createParser (/mnt/vda3/project/node_modules/jison/lib/jison.js:1327:13), <anonymous>:81:21)
    at Object.parseError (eval at RegExpLexer (/mnt/vda3/project/node_modules/jison-lex/regexp-lexer.js:124:17), <anonymous>:7:28)
    at Object.next (eval at RegExpLexer (/mnt/vda3/project/node_modules/jison-lex/regexp-lexer.js:124:17), <anonymous>:262:25)
    at Object.lex (eval at RegExpLexer (/mnt/vda3/project/node_modules/jison-lex/regexp-lexer.js:124:17), <anonymous>:272:22)
    at lex (eval at createParser (/mnt/vda3/project/node_modules/jison/lib/jison.js:1327:13), <anonymous>:118:27)
    at Parser.parse (eval at createParser (/mnt/vda3/project/node_modules/jison/lib/jison.js:1327:13), <anonymous>:131:26)
    at Object.parse (/mnt/vda3/project/node_modules/gml2json/index.js:13:19)
```

**Comment by aressler38** [comment]
Try again, but this time remove the XML declaration. If the problem persists, then you need to provide the XML content that reproduces the error.

**Comment by gg187on** [comment]
```
Lexical error on line 2. Unrecognized text.
<eop:Mask xmlns:eop=
^
Error: Lexical error on line 2. Unrecognized text.
<eop:Mask xmlns:eop=
^
    at Parser.parseError (eval at createParser (/mnt/vda3/project/node_modules/jison/lib/jison.js:1327:13), <anonymous>:81:21)
    at Object.parseError (eval at RegExpLexer (/mnt/vda3/project/node_modules/jison-lex/regexp-lexer.js:124:17), <anonymous>:7:28)
    at Object.next (eval at RegExpLexer (/mnt/vda3/project/node_modules/jison-lex/regexp-lexer.js:124:17), <anonymous>:262:25)
    at Object.lex (eval at RegExpLexer (/mnt/vda3/project/node_modules/jison-lex/regexp-lexer.js:124:17), <anonymous>:272:22)
    at Object.lex (eval at RegExpLexer (/mnt/vda3/project/node_modules/jison-lex/regexp-lexer.js:124:17), <anonymous>:276:25)
    at lex (eval at createParser (/mnt/vda3/project/node_modules/jison/lib/jison.js:1327:13), <anonymous>:118:27)
    at Parser.parse (eval at createParser (/mnt/vda3/project/node_modules/jison/lib/jison.js:1327:13), <anonymous>:131:26)
    at Object.parse (/mnt/vda3/project/node_modules/gml2json/index.js:13:19)
```

```
let data = gml2json.parse(file.replace('<?xml version="1.0" encoding="UTF-8"?>', ''));
```

**Comment by gg187on** [comment]
My GML file is from Sentinel2 Open Access Hub.

**Comment by aressler38** [comment]
I believe you may be using this tool and thinking that gml is "geographical markup language." This is for graph modeling language. Sorry for the mixup. This is intended for the type of file described here: https://en.m.wikipedia.org/wiki/Graph_Modelling_Language

**Comment by gg187on** [comment]
Oh sorry,... :facepalm:
